---
- include_tasks: lfs-repo.yml
- name: Install Git
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - git-lfs
  become: true
- name: Install Git GUI
  apt: name={{item}} state=present
  with_items:
    - git-gui
    - gitk
  become: true
  when: git_install_gui
- name: Install Git Cola
  apt: name={{item}} state=present
  with_items:
    - git-cola
  become: true
  when: git_install_git_cola

- name: Install SCM Breeze
  git:
    repo: https://github.com/scmbreeze/scm_breeze.git
    dest: "{{homedir}}/.scm_breeze"
    depth: 1
    version: "dec2fff0bf4a5160837e6c1b92470336a60c2a98"
  when: git_install_scm_breeze is defined and git_install_scm_breeze == true
- name: Enable SCM Breeze
  shell: "{{homedir}}/.scm_breeze/install.sh"
  args:
    creates: "{{homedir}}/.scmbrc"
  when: git_install_scm_breeze is defined and git_install_scm_breeze == true

- name: Set name for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: user
    option: name
    value: "{{username}}"
  when: username is defined
- name: Set mail for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: user
    option: email
    value: "{{usermail}}"
  when: usermail is defined
- name: Set push to simple for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: push
    option: default
    value: simple
- name: Set askpass if it was defined
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: core
    option: askpass
    value: "{{askpass}}"
  when: askpass is defined
- name: Enable rebase for git pull by default
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: pull
    option: rebase
    value: "true"
  when: git_rebase_default is defined and git_rebase_default == true

- name: Enable colors for the bash prompt
  lineinfile:
    path: "{{homedir}}/.bashrc"
    regexp: "force_color_prompt="
    line: "force_color_prompt=yes"

- name: Set colorful prompt showing the git status
  lineinfile:
    path: "{{homedir}}/.bashrc"
    regexp: 'PS1=.*\\033'
    line: "PS1='`if [ $? = 0 ]; then echo \"\\[\\e[32m\\] ✔ \"; else echo \"\\[\\e[31m\\] ✘ \"; fi`\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\e[01;34m\\]\\w\\[\\e[00;34m\\] `(( $(git status --porcelain 2>/dev/null | wc -l) == 0 )) && echo \"\\[\\e[01;32m\\]\" || ( (( $(git status --porcelain --untracked-files=no 2>/dev/null | wc -l) > 0 )) && echo \"\\[\\e[01;31m\\]\" ) || echo \"\\[\\e[01;33m\\]\"`$(__git_ps1 \"(%s)\")`echo \"\\[\\e[00m\\]\"`\\$ '"

- include_tasks: config-kde.yml
  when: desktop_environment is defined and desktop_environment == "KDE"
