---
- script: git-lfs-install.deb.sh
  args:
    creates: /etc/apt/sources.list.d/github_git-lfs.list
  become: true
- name: Install Git
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - git
    - git-lfs
  become: true
- name: Set name for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: user
    option: name
    value: "{{username}}"
  when: username is defined
- name: Set mail for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: user
    option: email
    value: "{{usermail}}"
  when: usermail is defined
- name: Set push to simple for Git
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: push
    option: default
    value: simple
- name: Set askpass if it was defined
  ini_file:
    path: "{{homedir}}/.gitconfig"
    section: core
    option: askpass
    value: "{{askpass}}"
  when: askpass is defined
